# This is a basic workflow that is manually triggered
name: Trigger Airtable Validation

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  schedule:
    # sets the action to run daily. You can modify this to run the action more or less freqently
    - cron: '5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_airtable_validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook@69ec4d54b364f01d0be541be2ca4f826e63878d3
      env:
        webhook_url: "https://gameworkersolidarity.com/api/validateAirtableData"
        webhook_secret: ""